<section class="contact container">

	<h1>Restons en contact</h1>

	<div class="flex">

		<div>	
			<!-- Address -->
			<article>
				<h2>Nous trouver</h2>
				<address>
					<p>2 bis rue Saint Vincent</p>
					<p>44430 Le Landreau</p>
					<p><a href="tel:+3340037631">02 40 03 76 31</a></p>
				</address>
			</article>

			<!-- Opening times -->
			<article>
				<h2>Horaires d'ouverture</h2>
				<p>Mercredi : 10h30-12h30 / 14h00-18h30</p>
				<p>Vendredi : 15h30-18h30</p>
				<p>Samedi :	10h30-12h30</p>
			</article>
		</div>

		<!-- Maps -->
		<article>
			<h2>Pour vous y rendre</h2>
			<a href="https://www.google.com/maps/place/2+Rue+Saint-Vincent,+44430+Le+Landreau/@47.2037341,-1.3083655,17z/data=!3m1!4b1!4m9!1m2!2m1!1smaps+2+bis+rue+Saint+Vincent++44430+Le+Landreau++02+40+03+76+31!3m5!1s0x48060a0110129521:0xb5494854890487f2!8m2!3d47.2037305!4d-1.3061768!15sCj9tYXBzIDIgYmlzIHJ1ZSBTYWludCBWaW5jZW50ICA0NDQzMCBMZSBMYW5kcmVhdSAgMDIgNDAgMDMgNzYgMzGSARFjb21wb3VuZF9idWlsZGluZw">
				<i class="fas fa-map-marked-alt"></i>
			</a>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2710.6565676808586!2d-1.3083654842407861!3d47.20373412371332!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48060a0110129521%3A0xb5494854890487f2!2s2%20Rue%20Saint-Vincent%2C%2044430%20Le%20Landreau!5e0!3m2!1sfr!2sfr!4v1620104918046!5m2!1sfr!2sfr" allowfullscreen="" loading="lazy"></iframe>
		</article>
	</div>
	
</section>
