<section class="home container">
	
	<h1>Bienvenue dans votre bibliothèque du Landreau</h1>
	
	<!-- BANNER -->
	<img class="banner" src="https://www.normandielivre.fr/wp-content/uploads/2020/04/p_9_le_conquerant_copyright-Librairie-du-ConquC%CC%A7rant-copie-768x464-e1585837852907.jpg" alt="image de librairie">

	<!-- ARTICLES -->
	<article>
	    <h2>Vos auteurs préférés</h2>
	    <img class="floatLeft" src="img/presentation.jpg" alt="image de livre pour nos valeurs">
	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, obcaecati, minima, ipsam officia aperiam nihil doloribus nobis dolorum pariatur nulla quidem consectetur laborum impedit hic sequi. Deleniti, autem, cupiditate, labore temporibus placeat non maiores. Deleniti, autem, cupiditate, labore temporibus placeat non maiores.</p>
	</article>

	<article>
	    <h2>Des livres sur tous les thèmes</h2>
	    <img class="floatRight" src="img/knowledge.jpg" alt="image sur la connaissance">
	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, obcaecati, minima, ipsam officia aperiam nihil doloribus nobis dolorum pariatur nulla quidem consectetur laborum impedit hic sequi. Deleniti, autem, cupiditate, labore temporibus placeat non maiores.</p>
	</article>
	
	<article>
	    <h2>Savoir se retrouver en famille</h2>
	    <img class="floatLeft" src="img/family.jpg" alt="image d'une grand-mère qui lit un roman à ses petits-enfants">
	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, obcaecati, minima, ipsam officia aperiam nihil doloribus nobis dolorum pariatur nulla quidem consectetur laborum impedit hic sequi. Deleniti, autem, cupiditate, labore temporibus placeat non maiores. Deleniti, autem, cupiditate, labore temporibus placeat non maiores.</p>
	</article>
	
	<article>
	    <h2>Les plus belles collections</h2>
	    <img class="floatRight" src="img/collections.jpg" alt="représentation de collections de livres">
	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, obcaecati, minima, ipsam officia aperiam nihil doloribus nobis dolorum pariatur nulla quidem consectetur laborum impedit hic sequi. Deleniti, autem, cupiditate, labore temporibus placeat non maiores.</p>
	</article>

</section>