<section class="register container">
		
	<h1>Inscrivez-vous</h1>
	
	<div id="return"></div>
	
	<form id="registerUser" method="post" class="form">

		<input type="text" name="lastname_user" placeholder="Votre nom : "/>
		<input type="text" name="firstname_user" placeholder="Votre prénom : "/>
		<input type="text" name="mail_user" placeholder="Votre mail : "/>
		<input type="password" name="password_user" placeholder="Choisissez un mot de passe"/>
		<input type="password" name="cpassword_user" placeholder="Confirmez le mot de passe"/>    
		
		<button type="submit">Envoyer</button>

	</form>
	
</section>
